# Generated by Django 4.1.3 on 2023-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=32)),
                ('Surname', models.CharField(max_length=32)),
                ('Email', models.EmailField(max_length=64)),
                ('Telephone', models.CharField(max_length=32)),
                ('Username', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=60)),
                ('Title', models.CharField(max_length=4)),
                ('DateOfBirth', models.DateField()),
                ('DateJoined', models.DateField()),
                ('IsActivated', models.BooleanField()),
            ],
        ),
    ]
