# Generated by Django 4.1.3 on 2023-01-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
