# Generated by Django 4.1.3 on 2023-01-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerSection', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=32)),
                ('Surname', models.CharField(max_length=32)),
                ('Email', models.EmailField(max_length=64)),
                ('Telephone', models.CharField(max_length=32)),
                ('Username', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=60)),
                ('Title', models.CharField(max_length=4)),
                ('DateOfBirth', models.DateField()),
                ('DateJoined', models.DateField()),
                ('IsActivated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=256)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=256)),
                ('StarRating', models.IntegerField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerSection.customer')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerSection.item')),
            ],
        ),
    ]
