# Generated by Django 4.1.3 on 2023-02-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0002_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Username',
            new_name='username',
        ),
    ]
