# Generated by Django 4.1.3 on 2023-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustomerID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='IsActivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
