# Generated by Django 4.1.3 on 2023-01-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0004_alter_customer_customerid_alter_customer_isactivated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ItemID',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
