# Generated by Django 4.1.3 on 2023-02-18 15:40

import customerSection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0004_alter_customer_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAction',
            fields=[
                ('Token', models.CharField(default=customerSection.models.generateToken, max_length=15, primary_key=True, serialize=False)),
                ('Reason', models.PositiveSmallIntegerField()),
                ('Action', models.CharField(max_length=255)),
            ],
        ),
    ]
