# Generated by Django 4.1.3 on 2023-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0005_tokenaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
