# Generated by Django 4.1.3 on 2023-01-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerSection', '0005_remove_review_customerid_remove_review_itemid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=32)),
                ('Surname', models.CharField(max_length=32)),
                ('Email', models.EmailField(max_length=64)),
                ('Telephone', models.CharField(max_length=32)),
                ('Username', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=60)),
                ('Title', models.CharField(max_length=4)),
                ('DateOfBirth', models.DateField()),
                ('DateJoined', models.DateField()),
                ('IsActivated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=256)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('ItemInstanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Size', models.CharField(max_length=3)),
                ('Colour', models.CharField(max_length=16)),
                ('Quantity', models.SmallIntegerField()),
                ('AmountSold', models.IntegerField()),
                ('IsPublic', models.BooleanField()),
                ('HighResImg', models.ImageField(height_field=1080, upload_to='', width_field=1080)),
                ('LowResImg', models.ImageField(height_field=256, upload_to='', width_field=256)),
                ('QBR', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ItemID', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.item')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.CharField(max_length=256)),
                ('StarRating', models.SmallIntegerField()),
                ('CustomerID', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.customer')),
                ('ItemID', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.item')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('OrderLineID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemInstanceID', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.iteminstance')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfSale', models.DateField()),
                ('PaymentMethod', models.CharField(max_length=32)),
                ('IsShipped', models.BooleanField(default=False)),
                ('Postcode', models.CharField(max_length=7)),
                ('AddressLine1', models.CharField(max_length=35)),
                ('AddressLine2', models.CharField(max_length=35)),
                ('City', models.CharField(max_length=26)),
                ('County', models.CharField(max_length=26)),
                ('CustomerID', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.customer')),
            ],
        ),
    ]
