# Generated by Django 4.1.3 on 2023-02-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('StyleID', models.AutoField(primary_key=True, serialize=False)),
                ('Size', models.CharField(max_length=3)),
                ('Colour', models.CharField(max_length=16)),
                ('Quantity', models.SmallIntegerField()),
                ('AmountSold', models.IntegerField()),
                ('IsPublic', models.BooleanField()),
                ('HighResImg', models.ImageField(height_field=1080, upload_to='', width_field=1080)),
                ('LowResImg', models.ImageField(height_field=256, upload_to='', width_field=256)),
                ('QBR', models.DecimalField(decimal_places=2, default=-1.0, max_digits=3)),
                ('ItemID', models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, related_name='ItemRef', to='customerSection.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='ItemInstanceID',
        ),
        migrations.AddField(
            model_name='orderline',
            name='OrderID',
            field=models.ForeignKey(db_column='', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customerSection.order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemInstance',
        ),
        migrations.AddField(
            model_name='orderline',
            name='StyleID',
            field=models.ForeignKey(db_column='', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='style', to='customerSection.style'),
            preserve_default=False,
        ),
    ]
