# Generated by Django 4.1.3 on 2023-02-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0007_style_remove_orderline_iteminstanceid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='HighResImg',
        ),
        migrations.RemoveField(
            model_name='style',
            name='LowResImg',
        ),
    ]
