# Generated by Django 4.1.3 on 2023-01-31 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0008_orderline_quantity_alter_customer_datejoined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DateJoined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='DateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Firstname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='IsActivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Surname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Telephone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Title',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Username',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='Title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='AmountSold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='Colour',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='HighResImg',
            field=models.ImageField(height_field=1080, upload_to='', width_field=1080),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='IsPublic',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='ItemID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.item'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='LowResImg',
            field=models.ImageField(height_field=256, upload_to='', width_field=256),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='QBR',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='Quantity',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='Size',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='AddressLine1',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='order',
            name='AddressLine2',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='City',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='order',
            name='County',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='CustomerID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='DateOfSale',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='IsShipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='Postcode',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='ItemInstanceID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.iteminstance'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='Quantity',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='Comment',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='review',
            name='CustomerID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ItemID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.item'),
        ),
        migrations.AlterField(
            model_name='review',
            name='StarRating',
            field=models.SmallIntegerField(),
        ),
    ]
