# Generated by Django 4.1.3 on 2023-02-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0009_alter_order_addressline2_alter_order_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='OrderID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='StyleID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.style'),
        ),
        migrations.AlterField(
            model_name='style',
            name='ItemID',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, to='customerSection.item'),
        ),
    ]
