# Generated by Django 4.1.3 on 2023-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0010_alter_orderline_orderid_alter_orderline_styleid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='LowResImg',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='style',
            name='AmountSold',
            field=models.IntegerField(default=0),
        ),
    ]
