# Generated by Django 4.1.3 on 2023-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0011_style_highresimg_style_lowresimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='LowResImg',
        ),
        migrations.AddField(
            model_name='style',
            name='HighResImg',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
