# Generated by Django 4.1.3 on 2023-03-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerSection', '0013_customer_basket_customer_wishlish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='wishlish',
            new_name='wishlist',
        ),
    ]
